services:
  backend:
    container_name: EventBooker
    build: 
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8080"
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"      
      - "443:443"    
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    